export const locations = [
  { value: "bloemfontein", label: "Bloemfontein", country: "South Africa" },
  { value: "cape-town", label: "Cape Town", country: "South Africa" },
  { value: "durban", label: "Durban", country: "South Africa" },
  { value: "east-london", label: "East London", country: "South Africa" },
  { value: "gqeberha", label: "Gqeberha (Port Elizabeth)", country: "South Africa" },
  { value: "johannesburg", label: "Johannesburg", country: "South Africa" },
  { value: "kimberley", label: "Kimberley", country: "South Africa" },
  { value: "mahikeng", label: "Mahikeng", country: "South Africa" },
  { value: "mbombela", label: "Mbombela", country: "South Africa" },
  { value: "nelspruit", label: "Nelspruit", country: "South Africa" },
  { value: "polokwane", label: "Polokwane", country: "South Africa" },
  { value: "pietermaritzburg", label: "Pietermaritzburg", country: "South Africa" },
  { value: "pretoria", label: "Pretoria", country: "South Africa" },
  { value: "rustenburg", label: "Rustenburg", country: "South Africa" },
  { value: "soweto", label: "Soweto", country: "South Africa" },
  { value: "stellenbosch", label: "Stellenbosch", country: "South Africa" },
  { value: "upington", label: "Upington", country: "South Africa" },
  { value: "vanderbijlpark", label: "Vanderbijlpark", country: "South Africa" },
  { value: "witbank", label: "Witbank", country: "South Africa" },
  { value: "potchefstroom", label: "Potchefstroom", country: "South Africa" },
  { value: "george", label: "George", country: "South Africa" },
  { value: "knysna", label: "Knysna", country: "South Africa" },
  { value: "mossel-bay", label: "Mossel Bay", country: "South Africa" },
  { value: "paarl", label: "Paarl", country: "South Africa" },
  { value: "somerset-west", label: "Somerset West", country: "South Africa" },
  { value: "benoni", label: "Benoni", country: "South Africa" },
  { value: "boksburg", label: "Boksburg", country: "South Africa" },
  { value: "brakpan", label: "Brakpan", country: "South Africa" },
  { value: "germiston", label: "Germiston", country: "South Africa" },
  { value: "krugersdorp", label: "Krugersdorp", country: "South Africa" },
  { value: "randburg", label: "Randburg", country: "South Africa" },
  { value: "roodepoort", label: "Roodepoort", country: "South Africa" },
  { value: "sandton", label: "Sandton", country: "South Africa" },
  { value: "centurion", label: "Centurion", country: "South Africa" },
  { value: "middelburg", label: "Middelburg", country: "South Africa" },
  { value: "secunda", label: "Secunda", country: "South Africa" },
];
